name: CI Checks

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: ^1.21
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Run Test
        run: make test
      - name: Coverage Check
        run: make coverage
      - name: Generate Report
        run: make report
      - name: Copy files
        run: |
          mkdir reports
          cp cover.html ./reports
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: reports

  build:
    name: Build App
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: ^1.21

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build
        run: make build

      - name: Copy Files
        run: |
          mkdir artifacts
          cp api ./artifacts

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: artifacts

  deliver:
    name: Release
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download binary
        uses: actions/download-artifact@v3
        with:
          name: api

      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            Still in experimentation phase
          draft: true
          prerelease: true
          files: api

  deploy-function:
    name: Deploy FaaS
    runs-on: ubuntu-22.04
    needs: test
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Authentication GCP
        id: 'auth'
        uses: google-github-actions/auth@v1
        with:
         credentials_json: ${{ secrets.GCP_CREDENTIALS }}
         service_account: hello-api@fluted-mercury-399512.iam.gserviceaccount.com
      - name: Deploy function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@v1
        with:
          name: translate
          entry_point: Translate
          runtime: go121
          credentials: ${{ secrets.GCP_CREDENTIALS }}
      - id: test
        run: curl "${{ steps.deploy.outputs.url }}/hello"
